on:
  push:
    branches:
      - master
    paths:
      - delegates/**/*
      - '!delegates/meta/delegates.json'
  workflow-dispatch:
jobs:
  upload_delegates:
    runs-on: ubuntu-latest
    name: Parses all the delegates and uploads all to IPFS.
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Upload
        id: upload
        uses: makerdao-dux/github-action-deploy-delegates@v1.1.17
        with:
          delegates-folder: 'delegates'
          tags-file: 'delegates/meta/tags.json'
          infura-id: ${{ secrets.INFURA_ID }}
          infura-secret: ${{ secrets.INFURA_KEY }}
          output-file: 'delegates/meta/delegates.json'
      # Use the output from the `upload` step
      - name: Get the output hash
        run: echo "The IPFS hash was ${{ steps.upload.outputs.hash }}"
      - name: Update pull request with delegates changes.
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'Added delegates aggregated file'
          add: 'delegates/meta/delegates.json'
          fetch: false
